# Generated by Django 4.2.10 on 2024-04-29 17:35

from django.db import migrations, models

from stock.enums import BaseStatus, BaseStatusColors


def create_base_statuses(apps, schema_editor):
    Status = apps.get_model("stock", "Status")
    statuses: list = []

    for idx, (base_status, color) in enumerate(zip(BaseStatus, BaseStatusColors), start=1):
        statuses.append(
            Status(
                name=base_status.label,
                status_code=base_status.value,
                color=color,
                is_deleted=False,
                position=idx,
                my_stock_status_name=base_status.label,
            )
        )

    Status.objects.bulk_create(statuses)


def delete_base_statuses(apps, schema_editor):
    Status = apps.get_model("stock", "Status")
    Status.objects.filter(name__in=BaseStatus.labels).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Имя статуса из маркетплейса"),
                ),
                (
                    "color",
                    models.CharField(max_length=7, verbose_name="Хекс код цвета вместе с #"),
                ),
                (
                    "status_code",
                    models.IntegerField(verbose_name="Целочисленный код статуса"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=True, verbose_name="Можно удалить"),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(verbose_name="Позиция в линейке статусов"),
                ),
                (
                    "my_stock_status_name",
                    models.CharField(
                        max_length=255,
                        verbose_name="Наименование статуса в 'Мой Склад'",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статус заказа на маркетплейсе",
                "verbose_name_plural": "Статусы заказов на маркетплейсах",
            },
        ),
        migrations.RunPython(create_base_statuses, reverse_code=delete_base_statuses)
    ]
