# Generated by Django 4.2.10 on 2024-05-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0002_order_rename_is_deleted_status_is_deletable_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="sticker",
            field=models.TextField(
                default="",
                verbose_name="Base64 представление стикера, получаемого по API",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="Количество"),
        ),
    ]
