# Generated by Django 4.2.10 on 2024-05-01 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0003_orderitem_sticker_alter_orderitem_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="shipped_dt",
            field=models.DateField(null=True, verbose_name="Дата и время отгрузки"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="stock.order",
            ),
        ),
    ]
