# Generated by Django 4.2.10 on 2024-04-01 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "auth_type",
                    models.CharField(
                        choices=[("BASIC", "basic"), ("TOKEN", "token")],
                        max_length=255,
                        verbose_name="Тип авторизации на платформе",
                    ),
                ),
                (
                    "auth_creds",
                    models.TextField(
                        verbose_name="Данные пользователя для входа на платформу"
                    ),
                ),
            ],
            options={
                "verbose_name": "Аккаунт пользователя на платформе",
                "verbose_name_plural": "Аккаунты пользователей на платформе",
            },
        ),
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "is_my_warehouse",
                    models.BooleanField(
                        default=False,
                        verbose_name="Нужен для определения того, является ли данная платформа моим складом (МойСклад 1с)",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="Название")),
                (
                    "sku",
                    models.CharField(
                        max_length=255, verbose_name="Идентификатор товара на платформе"
                    ),
                ),
                ("vendor", models.CharField(max_length=255, verbose_name="Артикул")),
                ("barcode", models.CharField(max_length=255, verbose_name="Баркод")),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="core.account",
                        verbose_name="Аккаунт к которому относятся продукты",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар на платформе",
                "verbose_name_plural": "Товары на платформе",
            },
        ),
        migrations.AddField(
            model_name="account",
            name="platform",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to="core.platform",
                verbose_name="Платформа, для которой заведен аккаунт",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь, которому принадлежит аккаунт",
            ),
        ),
    ]
