# Generated by Django 4.2.10 on 2024-04-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_account_platform_product_account_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='platform_type',
            field=models.IntegerField(choices=[(0, 'Wildberries'), (1, 'Yandex Market'), (2, 'Sber Market'), (3, 'OZON'), (4, 'Мой склад')], default=0, verbose_name='Платформа'),
        ),
    ]
