# Generated by Django 4.2.10 on 2024-04-03 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_platform_platform_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manual_connection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product'),
        ),
    ]
