# Generated by Django 4.2.10 on 2024-04-03 20:48

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_manual_connection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='is_my_warehouse',
        ),
        migrations.AddField(
            model_name='platform',
            name='authorization_fields',
            field=models.JSONField(default=core.models.default_authorization_fields, verbose_name='Описание полей в виде json'),
        ),
    ]
