# Generated by Django 4.2.10 on 2024-04-03 23:25

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_platform_is_my_warehouse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='auth_creds',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='authorization_fields',
        ),
        migrations.AddField(
            model_name='account',
            name='authorization_fields',
            field=models.JSONField(default=core.models.default_authorization_fields, verbose_name='Описание полей в виде json'),
        ),
    ]
