# Generated by Django 4.2.10 on 2024-04-04 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_account_auth_creds_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='auth_type',
        ),
    ]
