# Generated by Django 4.2.10 on 2024-04-06 12:43

from django.db import migrations, models

from core.enums import MarketplaceChoices


def create_initial_data(apps, schema_editor):
    Platform = apps.get_model("core", "Platform")
    for marketplace in MarketplaceChoices.choices:
        Platform.objects.create(name=marketplace[1], platform_type=marketplace[0])


def delete_initial_data(apps, schema_editor):
    Platform = apps.get_model("core", "Platform")
    Platform.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_account_auth_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platform",
            name="platform_type",
            field=models.IntegerField(
                choices=[
                    (0, "Wildberries"),
                    (1, "Яндекс Маркет"),
                    (2, "СберМаркет"),
                    (3, "OZON"),
                    (4, "Мой склад"),
                ],
                default=0,
                verbose_name="Платформа",
            ),
        ),
        migrations.RunPython(create_initial_data, reverse_code=delete_initial_data),
    ]
