# Generated by Django 4.2.10 on 2024-04-11 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_manual_connection_product_connection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connections', to='core.product'),
        ),
    ]
