# Generated by Django 4.2.10 on 2024-04-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_product_connection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platform",
            name="platform_type",
            field=models.IntegerField(
                choices=[
                    (0, "Wildberries"),
                    (1, "Яндекс Маркет"),
                    (2, "МегаМаркет"),
                    (3, "OZON"),
                    (4, "Мой склад"),
                ],
                default=0,
                verbose_name="Платформа",
            ),
        ),
    ]
