# Generated by Django 4.2.10 on 2024-04-30 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_platform_platform_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.TextField(blank=True, null=True, verbose_name='Бренд'),
        ),
    ]
