# Generated by Django 5.1 on 2024-08-25 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255, verbose_name='Категория товара')),
                ('dimensions', models.CharField(max_length=255, verbose_name='Габариты товара')),
                ('commission', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Комиссия')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='core.platform', verbose_name='Платформа')),
            ],
        ),
        migrations.CreateModel(
            name='MarketplaceLogistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255, verbose_name='Регион')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Логистические затраты')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistics', to='core.platform', verbose_name='Платформа')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название товара')),
                ('brand', models.TextField(blank=True, null=True, verbose_name='Бренд товара')),
                ('sku', models.CharField(max_length=255, verbose_name='Идентификатор товара на платформе')),
                ('vendor', models.CharField(max_length=255, verbose_name='Артикул товара')),
                ('barcode', models.JSONField(default=list, verbose_name='Баркод товара')),
                ('type', models.CharField(max_length=255, verbose_name='Тип товара(продукты, комплекты)')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена товара')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Себестоимость товара')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='core.account', verbose_name='Аккаунт')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='core.platform', verbose_name='Платформа')),
            ],
            options={
                'verbose_name': 'Продукт с ценами для Unit экономики',
                'verbose_name_plural': 'Продукты с ценами для Unit экономики',
            },
        ),
    ]
