# Generated by Django 4.2.10 on 2024-08-10 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0012_product_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена товара')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Себестоимость товара')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='core.platform', verbose_name='Платформа')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='core.product', verbose_name='Товар')),
            ],
        ),
        migrations.CreateModel(
            name='MarketplaceLogistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255, verbose_name='Регион')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Логистические затраты')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistics', to='core.platform', verbose_name='Платформа')),
            ],
        ),
        migrations.CreateModel(
            name='MarketplaceCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255, verbose_name='Категория товара')),
                ('dimensions', models.CharField(max_length=255, verbose_name='Габариты товара')),
                ('commission', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Комиссия')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='core.platform', verbose_name='Платформа')),
            ],
        ),
    ]
