# Generated by Django 4.2.10 on 2024-08-11 20:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_product_brand'),
        ('unit_economics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productprice',
            name='product',
        ),
        migrations.AddField(
            model_name='productprice',
            name='barcode',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Баркод товара'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productprice',
            name='brand',
            field=models.TextField(blank=True, null=True, verbose_name='Бренд товара'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='name',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Название товара'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productprice',
            name='sku',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Идентификатор товара на платформе'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productprice',
            name='type',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Тип товара(продукты, комплекты)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productprice',
            name='vendor',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Артикул товара'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productprice',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='core.platform', verbose_name='Платформа'),
        ),
    ]
