# Generated by Django 5.1 on 2024-08-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_economics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketplacecommission',
            name='category',
        ),
        migrations.RemoveField(
            model_name='marketplacecommission',
            name='commission',
        ),
        migrations.RemoveField(
            model_name='marketplacecommission',
            name='dimensions',
        ),
        migrations.AddField(
            model_name='marketplacecommission',
            name='category_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='marketplacecommission',
            name='category_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID категории'),
        ),
        migrations.AddField(
            model_name='marketplacecommission',
            name='dbs_commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Комиссия DBS'),
        ),
        migrations.AddField(
            model_name='marketplacecommission',
            name='fbo_commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Комиссия FBO'),
        ),
        migrations.AddField(
            model_name='marketplacecommission',
            name='fbs_commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Комиссия FBS'),
        ),
        migrations.AddField(
            model_name='marketplacecommission',
            name='fbs_express_commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Комиссия FBS Express'),
        ),
        migrations.AddField(
            model_name='marketplacelogistic',
            name='dimensions',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Габариты товара'),
        ),
    ]
