# Generated by Django 5.1 on 2024-08-27 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_economics', '0002_remove_marketplacecommission_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketplacecommission',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='marketplacelogistic',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='marketplacelogistic',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='marketplacelogistic',
            name='region',
        ),
        migrations.AddField(
            model_name='marketplacecommission',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_comission', to='unit_economics.productprice', verbose_name='Продукт'),
        ),
        migrations.AddField(
            model_name='marketplacelogistic',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_logisticcost', to='unit_economics.productprice', verbose_name='Продукт'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='length',
            field=models.IntegerField(blank=True, null=True, verbose_name='Длина'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='width',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ширина'),
        ),
    ]
