# Generated by Django 4.2.10 on 2024-08-12 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_product_brand'),
        ('unit_economics', '0002_remove_productprice_product_productprice_barcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprice',
            name='account',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='core.account', verbose_name='Аккаунт'),
            preserve_default=False,
        ),
    ]
