# Generated by Django 5.1 on 2024-08-27 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unit_economics', '0003_remove_marketplacecommission_platform_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productprice',
            old_name='type',
            new_name='product_type',
        ),
    ]
