# Generated by Django 5.1 on 2024-08-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_economics', '0004_rename_type_productprice_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprice',
            name='category_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='category_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер категории'),
        ),
    ]
