# Generated by Django 5.1 on 2024-08-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_economics', '0006_alter_productprice_category_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacelogistic',
            name='cost_logistic_fbo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Логистические затраты FBO'),
        ),
        migrations.AddField(
            model_name='marketplacelogistic',
            name='cost_logistic_fbs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Логистические затраты FBS'),
        ),
    ]
