# Generated by Django 5.1 on 2024-08-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_economics', '0007_marketplacelogistic_cost_logistic_fbo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplacelogistic',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Логистические затраты'),
        ),
    ]
