# Generated by Django 5.1 on 2024-08-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_economics', '0009_productprice_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Вес'),
        ),
    ]
