# Generated by Django 5.1 on 2024-08-30 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('unit_economics', '0010_alter_productprice_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketplacecommission',
            options={'verbose_name': 'Комиссия на Маркетплейсе', 'verbose_name_plural': 'Комиссия на Маркетплейсе'},
        ),
        migrations.AlterModelOptions(
            name='marketplacelogistic',
            options={'verbose_name': 'Логистические затраты на Маркетплейсе', 'verbose_name_plural': 'Логистические затраты на Маркетплейсе'},
        ),
        migrations.RemoveField(
            model_name='marketplacecommission',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='marketplacecommission',
            name='category_number',
        ),
        migrations.RemoveField(
            model_name='marketplacecommission',
            name='product',
        ),
        migrations.RemoveField(
            model_name='marketplacelogistic',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='category_number',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='height',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='length',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='width',
        ),
        migrations.CreateModel(
            name='MarketplaceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название товара')),
                ('brand', models.TextField(blank=True, null=True, verbose_name='Бренд товара')),
                ('sku', models.CharField(max_length=255, verbose_name='Идентификатор товара на платформе')),
                ('vendor', models.CharField(max_length=255, verbose_name='Артикул продавца')),
                ('barcode', models.JSONField(default=list, verbose_name='Баркод товара')),
                ('product_type', models.CharField(max_length=255, verbose_name='Тип товара(продукты, комплекты)')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена товара')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='Ширина')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Высота')),
                ('length', models.IntegerField(blank=True, null=True, verbose_name='Длина')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Вес')),
                ('category_number', models.IntegerField(blank=True, null=True, verbose_name='Номер категории')),
                ('category_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название категории')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mp_accounts', to='core.account', verbose_name='Аккаунт')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mp_plaform', to='core.platform', verbose_name='Платформа')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mp_product', to='unit_economics.productprice', verbose_name='ПРодукт на WB')),
            ],
            options={
                'verbose_name': 'Продукт на Маркетплейсе',
                'verbose_name_plural': 'Продукт на Маркетплейсе',
            },
        ),
        migrations.AddField(
            model_name='marketplacecommission',
            name='marketplace_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marketproduct_comission', to='unit_economics.marketplaceproduct', verbose_name='Продукт на маркетплейсе'),
        ),
        migrations.AddField(
            model_name='marketplacelogistic',
            name='marketplace_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marketproduct_logistic', to='unit_economics.marketplaceproduct', verbose_name='Продукт на маркетплейсе'),
        ),
    ]
