# Generated by Django 5.1 on 2024-08-30 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unit_economics', '0011_alter_marketplacecommission_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketplaceproduct',
            name='product_type',
        ),
    ]
